### ISSUE TITLE
vite build is running into an error

### ISSUE THREAD

**Issue by Tim-Obert** [s2b/vite-plugin-typo3#3]
```
[plugin-typo3-project]` undefined
error during build:
TypeError: Cannot read properties of undefined (reading 'debug')
    at configResolved (/var/www/html/node_modules/vite-plugin-typo3/dist/cjs/typo3project.js:71:30)
    at file:///var/www/html/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:66293:67
    at Array.map (<anonymous>)
    at resolveConfig (file:///var/www/html/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:66293:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async build (file:///var/www/html/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:65125:18)
    at async CAC.<anonymous> (file:///var/www/html/node_modules/vite/dist/node/cli.js:828:5)
Failed to run npm run build: exit status 1
```

vite.config.js is configured as described in the README

**Comment by s2b** [comment]
I can't reproduce this and I'm also not sure how this could even happen. But can you check if #5 solves your issue?
